# Generated by Django 6.0.5 on 2026-05-30 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cantidad_entradas', models.IntegerField()),
                ('monto_total', models.FloatField()),
                ('mercado_pago_redirect_url', models.TextField(blank=True, null=True)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comprar_entradas.formapago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comprar_entradas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='comprar_entradas.compra')),
                ('tipo_entrada', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='comprar_entradas.tipoentrada')),
            ],
        ),
    ]
