# Generated by Django 6.0.5 on 2026-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprar_entradas', '0002_auto_20260602_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='mercado_pago_redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
