[pytest]

DJANGO_SETTINGS_MODULE = core.settings

python_files = test_*.py

# Opcional: Evita que los avisos de depreciación (warnings) ensucien la salida de la consola
filterwarnings =
    ignore::DeprecationWarning